### ISSUE TITLE
Scalapack 2.1 PCHEEVR fails tests

### ISSUE THREAD

**Issue by JanneM** [amd/scalapack#1]
As the title says, both the binary supplied by AMD, and the version built by myself (gcc9.1, openmpi4.0.3 - I patch it for change of one deprecated function name) fails all tests using PCHEEVR.

In addition some tests fails or are skipped due to illegal input values; I don't know that this is a problem, though.

CentOS 8, gcc 9.1, openMPI 4.0.3. Also, building and testing on Intel hardware as our new cluster has not yet been delivered so we don't have access to the real nodes.

[ScalaPack_TestResults.txt](https://github.com/amd/scalapack/files/4296498/ScalaPack_TestResults.txt)

**Comment by pradeeptrgit** [comment]
Hi Jan,
Thanks for reporting your observations.

Our validation of ScaLAPACK tests on AMD EPYC CPUs with Ubuntu 18 has shown tests passing including PCHEEVR. On CentOS and SLES however we have observed few failures.

If possible, can you try with Ubuntu OS? In the meantime, we will give another shot at CentOS and find if any OS toolchain specific issues.

**Comment by pradeeptrgit** [comment]
Hi Jan,

We investigated this issue. Figured out that there is an issue in the test case of Netlib ScaLAPACK test suite. There are few variable initializations missing in the test cases. We will provide a fix for this in the corresponding test case and update it in our next AOCL release which is tentatively planned for going live in the next couple of months.

**Comment by JanneM** [comment]
Thank you. Great to know it was just a faulty testcase. And I'm sorry that I didn't get back to you on testing on other OS's; life (and a certain virus) intervened.

**Comment by pradeeptrgit** [comment]
The test case issue is fixed in latest AOCL 2.2 release. Closing this issue.
