### ISSUE TITLE
fork of Reference-ScaLAPACK/scalapack

### ISSUE THREAD

**Issue by zerothi** [amd/scalapack#2]
Why isn't this a fork of https://github.com/Reference-ScaLAPACK/scalapack

It seems to me that this is simply build on top of ScaLAPACK, so why not ensure you can easily track changes?

Could you clarify the intents of this code?
I.e. will you continue to have this code orthogonal to original ScaLAPACK? Or will you try and return developments to ScaLAPACK?

**Comment by pradeeptrgit** [comment]
Hi,
Thanks for your query. We do intend to upstream and return developments to Netlib repo of ScaLAPACK. We are keeping in sync with the Netlib version. We will keep community posted on the same when we are ready to upstream.

**Comment by zerothi** [comment]
But it seems weird not to do a proper fork then? It becomes (near) impossible for end-users to figure out how the two differ ;)

**Comment by zerothi** [comment]
Any news here?

**Comment by pradeeptrgit** [comment]
AMD has plans to include its latest ScaLAPACK changes in a fork of Reference ScaLAPACK in its next AOCL release. Expect an update before end of this year.

**Comment by zerothi** [comment]
So what are the plans to back-port improvements in such a way that they are not AMD specific? :)
I would hate to follow `N` different forks of a project to sustain a HPC environment dependent on the architecture... :(

**Comment by pradeeptrgit** [comment]
Any architecture specific changes would be controlled via separate build flags. Hence, if one is using AMD Zen based CPUs, they need to enable those flags while compiling.

**Comment by zerothi** [comment]
No, I mean that I, as a HPC environment maintainer do not want to install Reference/ScaLAPACK for non-AMD architectures and AMD/ScaLAPACK for AMD architectures. It does not make sense to try and figure out which scalapack version I should install for end-users...

**Comment by pradeeptrgit** [comment]
Once we upstream the fork changes , one can install from Reference/ScaLAPACK. However, that depends how soon the upstream maintainers review and accepts the changes.

**Comment by pradeeptrgit** [comment]
New version of ScaLAPACK library for AMD is released as part of AOCL 3.1 release. With this release, ScaLAPACK is now under a new repository https://github.com/amd/aocl-scalapack . This repo is a fork from the upstream Reference/ScaLAPACK

More details on AOCL 3.1 release here https://developer.amd.com/amd-aocl/

**Comment by zerothi** [comment]
ok, will you then close this repo?

**Comment by pradeeptrgit** [comment]
This repo will be read-only. All future updates will be on the new repo

**Comment by zerothi** [comment]
Ok, so you'll archive the repo. Great!
