### ISSUE TITLE
Not finding liblapack.a

### ISSUE THREAD

**Issue by chrisreidy** [amd/scalapack#3]
63% through the build I get
make[2]: *** No rule to make target `lib/liblapack.a', needed by `lib/libscalapack.so'.  Stop.
I use:
-DLAPACK_LIBRARIES=/path/to/apps/aocl-libflame/2.2/lib/libflame.a
Also in the lib directory is liblapacke.a whereas the build is looking for liblapack.a.
I do have an atlas module with ../atlas/3.10.3/lib/liblapack.a but I am trying to follow the AOCL User Guide as closely as possible
Full cmake
cmake .. -DCMAKE_INSTALL_PREFIX=/path/to/apps/aocl-scalapack/2.2 -DBUILD_SHARED_LIBS=ON -DBLAS_LIBRARIES=/path/to/apps/aocl-blis/2.2/lib/libblas.a -DLAPACK_LIBRARIES=/path/to/apps/aocl-libflame/2.2/lib/libflame.a -DCMAKE_C_COMPILER=mpicc -DCMAKE_Fortran_COMPILER=mpif90 -DUSE_OPTIMIZED_LAPACK_BLAS=OFF -DUSE_F2C=ON

**Comment by pradeeptrgit** [comment]
Hi,

Can you reconfirm libflame library is located at  "/path/to/apps/aocl-libflame/2.2/lib/libflame.a" path? It looks like configuration was not able to find the lapack library i.e. libflame in this case. 

Also, can you post the complete output of cmake run?

**Comment by chrisreidy** [comment]
Hi
Here are the contents of 'ls /opt/ohpc/pub/apps/aocl-libflame/2.2/lib/'
libflame.a  libflame.so  libflame.so.2  libflame.so.2.2  liblapacke.a

Here is the cmake run:
-- The C compiler identification is GNU 8.3.0
-- The Fortran compiler identification is GNU 8.3.0
-- Check for working C compiler: /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicc
-- Check for working C compiler: /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Fortran compiler: /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpif90
-- Check for working Fortran compiler: /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpif90  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpif90 supports Fortran 90
-- Checking whether /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpif90 supports Fortran 90 -- yes
-- Found MPI_C: /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicc (found version "3.1") 
-- Found MPI_Fortran: /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpif90 (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Found MPI_LIBRARY : TRUE 
-- --> MPI C Compiler : /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicc
-- --> C Compiler : /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicc
-- --> MPI Fortran Compiler : /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpif90
-- --> Fortran Compiler : /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpif90
-- Reducing RELEASE optimization level to O2
-- =========
-- Compiling and Building BLACS INSTALL Testing to set correct variables
-- Configure in the INSTALL directory successful
-- Build in the BLACS INSTALL directory successful
-- =========
-- Testing FORTRAN_MANGLING
-- CDEFS set to Add_
-- =========
-- CHECKING BLAS AND LAPACK LIBRARIES
-- --> LAPACK supplied by user is /opt/ohpc/pub/apps/aocl-libflame/2.2/lib/libflame.a.
-- Looking for Fortran dgesv
-- Looking for Fortran dgesv - not found
-- --> LAPACK routine dgesv is found: .
-- --> LAPACK and BLAS were not found. Reference LAPACK and BLAS will be downloaded and installed
-- BLAS library: /opt/ohpc/admin/UAbuild/aocl-scalapack/scalapack-2.2/build/lib/libblas.a
-- LAPACK library: /opt/ohpc/admin/UAbuild/aocl-scalapack/scalapack-2.2/build/lib/liblapack.a
-- =========
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/ohpc/admin/UAbuild/aocl-scalapack/scalapack-2.2/build

It is odd that LAPACK and BLAS were not found.  They are installed in the OS:
rpm -qa |grep blas
blas-devel-3.4.2-8.el7.x86_64
libcublas-devel-11-0-11.2.0.252-1.x86_64
blas-3.4.2-8.el7.x86_64
libcublas-11-0-11.2.0.252-1.x86_64
openblas-gnu8-ohpc-0.3.7-5.1.ohpc.1.3.9.x86_64
(base) [chrisreidy@cleese aocl-scalapack]$ rpm -qa |grep lapack
lapack-3.4.2-8.el7.x86_64
lapack-devel-3.4.2-8.el7.x86_64
scalapack-gnu8-openmpi3-ohpc-2.0.2-27.4.ohpc.1.3.6.x86_64

**Comment by pradeeptrgit** [comment]
The BLIS library name is misspelt. It should be libbl**i**s.a. In your path, its mentioned as libbl**a**s.a. 
/path/to/apps/aocl-blis/2.2/lib/libbl**i**s.a

**Comment by chrisreidy** [comment]
Oh - I am not sure how many times I read blas and it should have been blis.
Compiles now, thanks
